// Embedded pinyin IME engine. Loads the pinyin → candidates dictionary
// generated by scripts/gen-pinyin-dict.mjs and answers candidate queries for a
// raw keystroke buffer (toneless pinyin, no separators).

type PinyinDict = Record<string, string[]>

// Every toneless syllable that occurs in the generated dictionary (Google
// Pinyin typing conventions: ü is typed as v in lv/nv and as ue in lue/nue).
const SYLLABLE_LIST = `
  a ai an ang ao ba bai ban bang bao bei ben beng bi bian biao bie bin bing bo bu ca cai can cang
  cao ce cen ceng cha chai chan chang chao che chen cheng chi chong chou chu chua chuai chuan
  chuang chui chun chuo ci cong cou cu cuan cui cun cuo da dai dan dang dao de dei den deng di dia
  dian diao die ding diu dong dou du duan dui dun duo e ei en eng er fa fan fang fei fen feng fiao
  fo fou fu ga gai gan gang gao ge gei gen geng gong gou gu gua guai guan guang gui gun guo ha hai
  han hang hao he hei hen heng hm hng hong hou hu hua huai huan huang hui hun huo ji jia jian
  jiang jiao jie jin jing jiong jiu ju juan jue jun ka kai kan kang kao ke kei ken keng kong kou
  ku kua kuai kuan kuang kui kun kuo la lai lan lang lao le lei leng li lia lian liang liao lie
  lin ling liu lo long lou lu luan lue lun luo lv m ma mai man mang mao me mei men meng mi mian
  miao mie min ming miu mo mou mu n na nai nan nang nao ne nei nen neng ng ni nian niang niao nie
  nin ning niu nong nou nu nuan nue nuo nv o ou pa pai pan pang pao pei pen peng pi pian piao pie
  pin ping po pou pu qi qia qian qiang qiao qie qin qing qiong qiu qu quan que qun ran rang rao re
  ren reng ri rong rou ru ruan rui run ruo sa sai san sang sao se sen seng sha shai shan shang
  shao she shei shen sheng shi shou shu shua shuai shuan shuang shui shun shuo si song sou su suan
  sui sun suo ta tai tan tang tao te tei teng ti tian tiao tie ting tong tou tu tuan tui tun tuo
  wa wai wan wang wei wen weng wo wu xi xia xian xiang xiao xie xin xing xiong xiu xu xuan xue xun
  ya yan yang yao ye yi yin ying yo yong you yu yuan yue yun za zai zan zang zao ze zei zen zeng
  zha zhai zhan zhang zhao zhe zhei zhen zheng zhi zhong zhou zhu zhua zhuai zhuan zhuang zhui
  zhun zhuo zi zong zou zu zuan zui zun zuo
`

const SYLLABLES = new Set(SYLLABLE_LIST.split(/\s+/).filter(Boolean))
const MAX_SYLLABLE_LEN = 6

let dict: PinyinDict = {}
let sortedKeys: string[] = []
let ready = false
let loadPromise: Promise<void> | null = null

export function ensureDictLoaded(): Promise<void> {
  if (!loadPromise) {
    loadPromise = (async () => {
      try {
        // Served via the /assets/* wildcard route — the embedded server only
        // whitelists specific top-level paths, so the dict must live in assets.
        const res = await fetch('/assets/pinyin-dict.json')
        if (!res.ok) return
        dict = (await res.json()) as PinyinDict
        sortedKeys = Object.keys(dict).sort()
        ready = true
      } catch {
        // Offline or asset missing: the IME simply offers no candidates.
      }
    })()
  }
  return loadPromise
}

export function isDictReady(): boolean {
  return ready
}

// Guards against prototype pollution: "constructor" etc. are typeable buffers.
function lookup(key: string): string[] | undefined {
  return Object.prototype.hasOwnProperty.call(dict, key) ? dict[key] : undefined
}

/** Greedy longest-match segmentation of the leading complete syllables. */
function segment(input: string): string[] {
  const syllables: string[] = []
  let pos = 0
  while (pos < input.length) {
    let matched = ''
    for (let len = Math.min(MAX_SYLLABLE_LEN, input.length - pos); len >= 1; len--) {
      const part = input.slice(pos, pos + len)
      if (SYLLABLES.has(part)) {
        matched = part
        break
      }
    }
    if (!matched) break
    syllables.push(matched)
    pos += matched.length
  }
  return syllables
}

/** Dictionary keys starting with `prefix`, shortest (most complete match) first. */
function keysWithPrefix(prefix: string): string[] {
  let lo = 0
  let hi = sortedKeys.length
  while (lo < hi) {
    const mid = (lo + hi) >> 1
    if (sortedKeys[mid] < prefix) lo = mid + 1
    else hi = mid
  }
  const matched: string[] = []
  for (let i = lo; i < sortedKeys.length && sortedKeys[i].startsWith(prefix); i++) {
    matched.push(sortedKeys[i])
  }
  return matched.sort((a, b) => a.length - b.length || (a < b ? -1 : 1))
}

export function queryCandidates(buffer: string, limit = 40): string[] {
  // Keep letters only (drops apostrophes and stray digits) and map the lve/nve
  // spellings of ü to the lue/nue forms the dictionary uses.
  const input = buffer
    .toLowerCase()
    .replace(/[^a-z]/g, '')
    .replace(/([ln])ve/g, '$1ue')
  if (input === '' || sortedKeys.length === 0) return []

  const out: string[] = []
  const seen = new Set<string>()
  const take = (candidates: string[] | undefined): boolean => {
    for (const c of candidates ?? []) {
      if (out.length >= limit) return true
      if (!seen.has(c)) {
        seen.add(c)
        out.push(c)
      }
    }
    return out.length >= limit
  }

  // 1. Exact key match.
  take(lookup(input))

  // 2. Keys the buffer is a strict prefix of (last syllable partially typed).
  if (out.length < limit) {
    for (const key of keysWithPrefix(input)) {
      if (key !== input && take(lookup(key))) break
    }
  }

  // 3. Whole buffer matched nothing: fall back to the longest leading syllable
  //    sequence with candidates so the user can commit piece by piece.
  if (out.length === 0) {
    const syllables = segment(input)
    for (let n = syllables.length; n >= 1; n--) {
      const key = syllables.slice(0, n).join('')
      if (key.length === input.length) continue // already tried as exact match
      const candidates = lookup(key)
      if (candidates) {
        take(candidates)
        break
      }
    }
  }

  return out
}
